# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(574, 344)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(60, 70, 441, 171))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.chooseLabel = QtWidgets.QLabel(self.widget)
        self.chooseLabel.setObjectName("chooseLabel")
        self.verticalLayout_2.addWidget(self.chooseLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditInput = QtWidgets.QLineEdit(self.widget)
        self.lineEditInput.setObjectName("lineEditInput")
        self.horizontalLayout_2.addWidget(self.lineEditInput)
        self.selectInputButton = QtWidgets.QPushButton(self.widget)
        self.selectInputButton.setObjectName("selectInputButton")
        self.horizontalLayout_2.addWidget(self.selectInputButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.outputLabel = QtWidgets.QLabel(self.widget)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_2.addWidget(self.outputLabel)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditOutput = QtWidgets.QLineEdit(self.widget)
        self.lineEditOutput.setObjectName("lineEditOutput")
        self.horizontalLayout_3.addWidget(self.lineEditOutput)
        self.selectOutputButton = QtWidgets.QPushButton(self.widget)
        self.selectOutputButton.setObjectName("selectOutputButton")
        self.horizontalLayout_3.addWidget(self.selectOutputButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.stressMarkButton = QtWidgets.QPushButton(self.widget)
        self.stressMarkButton.setObjectName("stressMarkButton")
        self.verticalLayout_2.addWidget(self.stressMarkButton)
        self.openOutputFolderButton = QtWidgets.QPushButton(self.widget)
        self.openOutputFolderButton.setObjectName("openOutputFolderButton")
        self.verticalLayout_2.addWidget(self.openOutputFolderButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 574, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.chooseLabel.setText(_translate("MainWindow", "Choose the ebook to you want to add stress marks to..."))
        self.selectInputButton.setText(_translate("MainWindow", "Select File..."))
        self.outputLabel.setText(_translate("MainWindow", "Output path"))
        self.selectOutputButton.setText(_translate("MainWindow", "Select File..."))
        self.stressMarkButton.setText(_translate("MainWindow", "Start stress marking"))
        self.openOutputFolderButton.setText(_translate("MainWindow", "Open output folder"))
